server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true             #开启动态路由
      routes:
      - id: payment_routh           #路由的ID，没有固定的规则但要求唯一，建议配合服务名
        uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
        predicates:
         - Path=/payment/get/**      #断言，路径相匹配的进行路由
      - id: payment_routh2           #路由的ID，没有固定的规则但要求唯一，建议配合服务名
        uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/lb      #断言，路径相匹配的进行路由
        - After=2020-09-10T16:30:48.547+08:00[Asia/Shanghai] #断言，当前时间在这时间之后进行路由
#        - Before=2020-09-10T16:30:48.547+08:00[Asia/Shanghai] #断言，当前时间在这时间之前进行路由
#        - Between=2020-09-10T16:30:48.547+08:00[Asia/Shanghai],2020-09-10T17:30:48.547+08:00[Asia/Shanghai] #断言，当前时间在这两个时间之间进行路由
#        - Cookie=username,zzyy #断言，当前请求的中有Cookie带有username,值为zzyy时则进行路由
#        - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
#        - Host=**.atguigu.com
#        - Hethod=Get
#        - Query=username,11  #username=11则进行路由




eureka:
  #修改显示名字
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否注册中心注册自己,默认为true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认为true ，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
