server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848 #注册中心

management:
  endpoints:
    web:
      exposure:
        include: "*"

service-url:
  nacos-user-service: http://nacos-payment-provider