server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangrengit/springcloud-config.git #Github上面的git仓库地址
          search-paths:
            - springcloud-config #仓库的名字
          basedir: tar/config #配置下拉下来的文件存放位置
      label: master #读取分支
    #rabbitmq相关配置
  rabbitmq:
    host: 192.168.0.111
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
        #交互地址
     service-url:
        defaultZone: http://eureka7001.com:7001/eureka



#暴露监控端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'